language: python
python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.8-dev"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install .
    - pip install smof
    - sudo apt-get install mafft
script: ./runtests.py && pip install . && cd test-data && ./test.sh && cd clades && ./test.sh
